import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import ScrollToTopButton from './components/ScrollToTopButton'
import Message from './components/message'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nuevo-Earth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href='/icon.png' />
      </head>
      <body className={inter.className} >
        <div>
        <Header />
        </div>
        {children}
        <Footer />
        {/* <ScrollToTopButton /> */}
        <div className='z-[1] fixed'>
        <Message/>
        </div> 
        
      </body>
    </html>
  )
}
